CREATE DATABASE my_catalog

CREATE TABLE books(
  id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  publish_date DATE,
  archived BOOLEAN,
  publisher VARCHAR(50),
  cover_state VARCHAR(50),
  title VARCHAR(50),
  author VARCHAR(50)
  genre_id INT,
  author_id INT,
  label_id INT,

  FOREIGN KEY(genre_id) REFERENCES genre(id)
  FOREIGN KEY(author_id) REFERENCES author(id)
  FOREIGN KEY(label_id) REFERENCES label(id)
);

CREATE TABLE labels(
  id GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(100),
  color VARCHAR(50)
);
